export const { 
    VITE_FIREBASE_API_KEY: API_KEY,
    VITE_FIREBASE_APP_ID: API_ID,
    VITE_FIREBASE_AUTH_DOMAIN: AUTH_DOMAIN,
    VITE_FIREBASE_PROJECT_ID: PROJECT_ID,
    VITE_FIREBASE_STORAGE_BUCKET: STORAGE_BUCKET,
    VITE_FIREBASE_MESSAGING_SENDER_ID: MESSAGING_SENDER_ID,
    VITE_FIREBASE_MEASUREMENT_ID: MEASUREMENT_ID,
    VITE_GEMINI_API_KEY: GEMINI_API_KEY,
    VITE_CLOUDINARY_CLOUD_NAME: CLOUD_NAME,
    VITE_CLOUDINARY_UPLOAD_PRESET: UPLOAD_PRESET,
} = import.meta.env;